export const REACT_LOGO = "https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg";
export const FIREBASE_LOGO = "https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg";
export const CHARTJS_LOGO = "https://www.chartjs.org/media/logo-title.svg"
export const CSS_LOGO = "https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
export const HTML_LOGO = "https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
export const JAVA_LOGO = "https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg"
export const JS_LOGO = "https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
export const MONGODB_LOGO = "https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
export const MYSQL_LOGO = "https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
export const PYTHON_LOGO = "https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg"
export const SPRING_LOGO = "https://www.vectorlogo.zone/logos/springio/springio-icon.svg"
export const TAILWIND_LOGO = "https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg"
export const AWS_LOGO = "https://media.licdn.com/dms/image/D4D12AQEmC2CSTK0unw/article-cover_image-shrink_600_2000/0/1691964348159?e=2147483647&v=beta&t=UA2DD5lAEDP28NHD9BRZIoriUAdwNxY8P465qku8lNY";
export const MATPLOTLIB_LOGO = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Matplotlib_icon.svg/180px-Matplotlib_icon.svg.png?20150311090915"
export const NUMPY_LOGO = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/512px-NumPy_logo_2020.svg.png"
export const SEABORN_LOGO = "https://seeklogo.com/images/S/seaborn-logo-244EB2DEC5-seeklogo.com.png"